version: '3.8'

services:
  boogle-maps:
    build:
      context: ./boogle-maps
      dockerfile: Dockerfile
    image: boogle-maps
    container_name: boogle-maps
    ports:
      - 9191:9191

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka
    ports:
      - 8761:8761

  pricing-service:
    build:
      context: ./pricing-service
      dockerfile: Dockerfile
    depends_on:
      - eureka
    image: pricing-service
    container_name: pricing-service
    ports:
      - 8082:8082

  vehicles-api:
    build:
      context: ./vehicles-api
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - boogle-maps
      - pricing-service
    image: vehicles-api
    container_name: vehicles-api
    ports:
      - 8080:8080